TrueFiEng/Waffle

- package.json
Running a build before publishing ensures you are not deploying an older version of your code by mistake.
> Build is now run automatically before publishing to NPM

- lib/compiler.ts
This was causing a build error on beta 9.
```
$ waffle waffle.json
TypeError: Cannot read property 'error' of undefined
at Compiler.<anonymous> (/Users/liam/src/code/monorepo/node_modules/ethereum-w
affle/dist/compiler.js:141:42)
at step (/Users/liam/src/code/monorepo/node_modules/ethereum-waffle/dist/compi
ler.js:43:23)
at Object.next (/Users/liam/src/code/monorepo/node_modules/ethereum-waffle/dis
t/compiler.js:24:53)
at fulfilled (/Users/liam/src/code/monorepo/node_modules/ethereum-waffle/dist/
compiler.js:15:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
at startup (internal/bootstrap/node.js:240:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```
> Set defaults for process and console in compiler

- README.md
`open-zeppelin` was renamed to `openzeppelin-solidity`. It was changed in smart contract code but not in README instructions
> Fix a typo in README dependency name

- package.json
- yarn.lock
The command `rm -rf` only works on unix-likes, thus the clean script fails on Windows. This replaces the command with the `rimraf` command from the package of the same name. It is a CLI tool that works identically to the `rm -rf` command, removing a file or an entire directory, but is implemented in platform-independent JS.
> Use rimraf in clean script instead of rm -rf

- .gitignore
- lib/compiler/buildUitls.ts
- lib/compiler/compileDocker.ts
- lib/compiler/compileNative.ts
- lib/compiler/compileSolcjs.ts
- lib/config/config.ts
- test/compiler/compilerOptions.ts
- test/projects/compilerOptions/config.json
- test/projects/compilerOptions/config_docker.json
- test/projects/compilerOptions/config_native.json
- test/projects/compilerOptions/contracts/Constantinople.sol
This allows passing low level options to the solidity compiler.
Fixes #82
> Add compilerOptions to config

- README.md
missing mentioning of ethereum docker image installation to pass the test.
> update README for passing end-to-end test locally

- lib/matchers/matchers.ts
Resolving the condition described in issue #95.
With an external Ganache client, use the `message` attribute of the transaction response, `reason` is an object that `toString()` does not serialize properly.
>  Added support to Ganache revert reason in transaction responses

- docs/release-notes/2.0.10.md
- docs/source/configuration.rst
- lib/compiler/saveOutput.ts
- lib/config/config.ts
- test/compiler/e2e.ts
- test/projects/custom/config_combined.js
added three possible versions of generated output:
* singleton json file for each sol file (default)
* one combined json for all (KLAB friendly)
* both of above
> adding new possible version of generated output of compilation (KLAB friendly)

- package.json
- test/fixtures.ts
- test/projects/example/Check.sol
changing ganache to 2.5.5 and new tests, covering fixture bug from ganache 2.4.0, added
> Ganache to 2.5.5 (fixes bug related to fixture)

- package.json
- yarn.lock
Update the `@resolver-engine/imports` and `@resolver-engine/imports-fs` dependencies to version `^0.3.3`, fixing #92.
> Update resolver-engine to 0.3.3 to fix issue with windows paths

- lib/waffle.ts
- test/deployContract.ts
Checks if the bytecode is empty when deploying the contract. If bytecode is empty throws error.
> Throw error in deployContract if bytecode empty

- package.json
- test/matchers/reverted.ts
- yarn.lock
There is new ganache-core which unfortunately is buggy and this is why I fixed version 2.6.1. Also yarn.lock hasn't been updated for a long time, so I update it to use the same packages' versions during development as users when they add Waffle as a dependency.
> Fix ganache-core version, yarn.lock update

- docs/source/features.rst
- lib/config/config.ts
- lib/waffle.ts
- test/projects/getGanacheOptions/config.json
- test/projects/getGanacheOptions/getGanacheOptions.ts
Added possibility to provide a path to a config file with Ganache options to createMockProvider.
https://github.com/EthWorks/Waffle/issues/112
> Add path to config parameter in createMockProvider

- README.md
- lib/matchers/matchers.ts
- test/matchers/events.ts
Update README to reflect API change for `chai` solidity matchers:
- `emitEvent` -> `emit`
> Fix #117: emit method name on docs

- lib/matchers/matchers.ts
- package.json
- test/matchers/contracts/events.sol
- test/matchers/events.ts
expected:
as        ```[ BigNumber { _hex: '0x01f4' }, BigNumber { _hex: '0x01f4' } ]``` 
equals ```[ BigNumber { _hex: '0x01f4' }, BigNumber { _hex: '0x01f4' } ]``` 
- it should passes the test
as        ```[ BigNumber { _hex: '0x01f4' }, BigNumber { _hex: '0x01f4' } ]``` 
equals ```[ 500, 500 ]``` 
- it should passes the test
actual:
```
AssertionError: expected [ Array(2) ] to equal [ Array(2) ]
at assertArgsArraysEqual (src/test/productAssetIdentity.spec.ts:65:51)
at derivedPromise.promise.then (src/test/productAssetIdentity.spec.ts:71:9)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
```
AssertionError: expected [ Array(2) ] to equal [ 500, 500 ]
at assertArgsArraysEqual (src/test/productAssetIdentity.spec.ts:65:51)
at derivedPromise.promise.then …
```
> quick fix to handle BigNumbers array as argument of the event log

- waffle-mock-contract/README.md
- waffle-mock-contract/src/index.ts
- waffle-mock-contract/test/contract.test.ts
- waffle-mock-contract/test/helpers/contracts/CounterOverloaded.sol
Addresses issue https://github.com/EthWorks/Waffle/issues/289.
Copied here:
The mock functions are keyed only on the function name, so if there are multiple functions with the same name only one is available.
This is ideal in most situations, but it would be great if we could also key on the full function signature (like ethers). For example:
```javascript
await token.mock.mint.withArgs(user1, 10000)
// can be 
await token.mock['mint(address,uint256)'].withArgs(user1, 10000)
```
This would be a very small and beneficial change.
> Added ability to lookup mock function by signature.

- waffle-chai/README.md
I needed to use these matchers directly without the rest of the Waffle project. The instructions for doing this could be more descriptive, so I added a little extra info.
> Add waffle-chai usage example

- waffle-compiler/src/config/loadConfig.ts
Right now the below command runs waffle with the default `waffle.json` config file if it is present in the current working directory:
```
waffle custom-config.json
```
This PR fixes this behaviour.
> Enable loading of custom config files when `waffle.json` is present

- docs/source/getting-started.rst
The default config of waffle looks for contracts in `src/`, not in `contracts/`, so I corrected the path.
> [docs] Fix the path to the example contract

- waffle-chai/src/matchers/emit.ts
- waffle-chai/test/matchers/events.test.ts
Context:
```solidity
function emitOne() public {
emit One(1, "One", 0x00cFBbaF7DDB3a1476767101c12a0162e241fbAD2a0162e2410cFBbaF7162123);
}
```
Currently the following test:
```js
await expect(events.emitOne())
.to.emit(events, 'One')
.withArgs(1, 'Two', '0x00cfbbaf7ddb3a1476767101c12a0162e241fbad2a0162e2410cfbbaf7162123');
```
returns the following error message:
```
AssertionError: expected 'Two' to equal 'One'
Expected :One
Actual   :Two
```
which is clearly wrong because `Two` is not the actual value.
This PR fixes the error messages so in the above case it looks like this:
```
AssertionError: expected 'One' to equal 'Two'
Expected :Two
Actual   :One
```
> Make emit matcher error messages follow chai convention

- waffle-chai/src/matchers/changeBalance.ts
- waffle-chai/src/matchers/changeBalances.ts
- waffle-provider/src/fixtures.ts
Hey @marekkirejczyk @sz-piotr,
I found some issues when using Waffle with Buidler, so I made this PR to fix them.
Some of Waffle's APIs use `Wallet` to type their parameters, but `Signer` could be used instead. This is a problem with Buidler because it sometimes connects to remote networks, and you can't have `Wallet`s in that case.
I changed the fixtures API, and in two chai matches, so that now they receive `Signer`. Luckily this is a backward-compatible change.
Now, the only uses of `Wallet` are left in the `MockProvider`, which I think makes sense.
Do you think we can get this into Waffle `3.0.2`?
> Replace uses of Wallet with Signer

- docs/source/matchers.rst
Was looking for this matches at the documentation and they were not there.
Then I saw that these matchers were added in the release (2.4.1 )[#214]
> adding extra BigNumber matchers to the docs

- waffle-mock-contract/README.md
- waffle-mock-contract/src/Doppelganger.sol
- waffle-mock-contract/src/index.ts
- waffle-mock-contract/test/contract.test.ts
- waffle-mock-contract/test/direct.test.ts
- call will execute a tx on behalf of a mock
- staticcall will call a constant fxn on behalf of a mock
> Mocks can now call and staticcall through to contracts

- package.json
- patches/ganache-core+2.10.2.patch
- waffle-provider/package.json
- yarn.lock
This should fix #281
Looks like line numbers problem was caused by ganache requireing "source-map-support/register".
After removing those requires, line numbers in failed tests are correct, but it needs further testing if it doesn't break anything else
> Fix source maps

- waffle-mock-contract/src/Doppelganger.sol
- waffle-mock-contract/src/index.ts
- waffle-mock-contract/test/contract.test.ts
Not being able to revert with a reason on a mock contract is prohibitively limiting.
Say you have contract A and contract B. The latter depends on the former. Say that the former throws specific errors depending on the state of the properties in the two contracts. If I mock contract A, I have to modify a lot of tests to revert with "Mock revert" instead of my bespoke error messages.
This PR does the following:
+ Adds a new `revertReason` property in the `MockCall` struct
+ Changes the signature of the `__waffle__mockReverts` function, by adding a second parameter `revertReason`
+ Adds a new function `revertWithReason` in the object returned by the `stub` function - which makes my change backwards-compatible!
+ Modifies the tests so that they work with the updated `__waffle__mockReverts` …
> Add revert with reason functionality for mock contracts

- docs/source/mock-contract.rst
As per #349, Waffle can now support arbitrary revert reasons when mocking a contract.
This PR documents the newly added behaviour.
> docs: mention "revertsWithReason"

- waffle-mock-contract/src/index.ts
- waffle-mock-contract/test/direct.test.ts
- waffle-mock-contract/test/helpers/contracts/Counter.sol
Adds missing spread syntax for the parameters for populateTransaction call as specified in [ethers v5 documentation](https://docs.ethers.io/v5/api/contract/contract/#contract-populateTransaction).
Closes #340
> Add missing spread operator

- docs/source/matchers.rst
Little wording change; the previous sentence seemed unfinished.
> Docs: replace "proper secret" with "proper private key"

- waffle-compiler/src/compileSolcjs.ts
For calculating solcjs binaries download paths we use a list of compiler versions fetched from [this github page](https://ethereum.github.io/solc-bin/bin/list.json). It seems the repository that publishes it [run out of disc space](https://github.com/ethereum/solc-bin/runs/1179669192) and the list has not been updated since September 26.
I changed the list url to point to the current version of the file taken directly from github repository.
> Make solcjs compilation work with versions >=0.7.2

- waffle-compiler/src/compileSolcjs.ts
- waffle-compiler/test/mocha.opts
Changes the version list url to `https://solc-bin.ethereum.org/bin/list.json`.
The change in mocha.opts is to prevent mocha from loading the cached versions of solc saved as js files.
@cameel I wanted to use the emscripten-wasm32 builds, but found that for some reason they aren't faster and using them made the tests timeout. I don't have more time to investigate the issue so we are sticking with `bin` for now.
Edit: the issue seems to only be related to node 10 #396. I suspect we will merge this PR and add support for wasm at a later date
> Correct version list url

- waffle-cli/README.md
The README.md was missing a single quote in one of the chai matchers.
> Fix missing single quote in README.md

- waffle-chai/src/matchers/bigNumber.ts
- waffle-chai/test/matchers/misc.test.ts
> Make BN matchers compatible with chai's lengthOf

- waffle-provider/src/MockProvider.ts
This fixes: https://github.com/EthWorks/Waffle/issues/281 (again)
EDIT:
After more investigation I realized that this is a bug only if a hardhat user imports anything from `waffle` rather than `waffle` provided in HRE. I feel like merging could improve life for some people but it boils down to a mistake on user's side.
> Lazy load ganache-core to avoid laoding `source-map-support` too early

- .changeset/selfish-shoes-tease.md
- waffle-ens/package.json
- waffle-provider/package.json
- yarn.lock
Ganache-core recently trimmed down a lot of its dependencies. It'd be nice if we moved to that version, to make the package smaller: https://github.com/trufflesuite/ganache-core/commit/a74efcec6b868e5778609dd95d26e5cd1f32e43a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519.
The `examples/` also need to be updated but I was not sure which version tag to assign.
> chore: use trimmed down ganache-core

- docs/source/getting-started.rst
Fixes #407 by making the sentence that suggests adding `ts-node` and `typecsript` explicit with a note and fuller sentences.
> make typescript note explicit

- waffle-compiler/package.json
- yarn.lock
`node-fetch@2.6.0` has a security advisory out. Although the advisory isn't relevant to waffle, it *does* result in the following dependabot alert:
the perfectionist in me would like for this alert to go away.
fixes #431
> fix: bump node-fetch version

- docs/source/configuration.rst
- examples/typechain/waffle.json
- waffle-cli/README.md
Some typechain related docs and configs were not correct (out-of-sync, typos etc.)
Now it's fixed.
> Fix typechain related docs and configs

- waffle-chai/src/matchers/bigNumber.ts
Chai has 3 ways to reference the `equal` assertion: `equal`, `eq`, and `equals` (ref https://github.com/chaijs/chai/blob/main/lib/chai/core/assertions.js#L1049-L1051). This adds the `equals` assertion to the overrides for BigNumbers
> Add `equals` override for BigNumber

- waffle-chai/src/matchers/emit.ts
Error thrown when event returns nullish/undefined parameter like empty string or empty array:
`     TypeError: Cannot read property 'length' of undefined
`
This pull request closes https://github.com/EthWorks/Waffle/issues/583
> 🧛‍♂️ Check for undefined event parameter

- waffle-chai/src/matchers/revertedWith.ts
- waffle-chai/test/matchers/reverted.test.ts
https://github.com/TrueFiEng/Waffle/issues/608
https://github.com/NomicFoundation/hardhat/issues/2234#issuecomment-1045974424
Supersedes https://github.com/TrueFiEng/Waffle/pull/627
> 🦊 Handle `revertedWith` with an empty `revertString`

- .changeset/brave-years-applaud.md
- docs/source/matchers.rst
- waffle-chai/src/index.ts
- waffle-chai/src/matchers/misc/struct.ts
- waffle-chai/src/matchers/withArgs.ts
- waffle-chai/src/matchers/withNamedArgs.ts
- waffle-chai/src/types.ts
- waffle-chai/test/matchers/events.test.ts
- waffle-chai/test/matchers/eventsTest.ts
Improved error messages for existing emit matchers
This is part of feature request https://github.com/EthWorks/Waffle/issues/437 to check against a subset of args emitted in events
> 💫 Added withNamedArgs method to the Chai emit matcher

- .changeset/beige-melons-prove.md
- waffle-chai/src/matchers/changeEtherBalance.ts
- waffle-chai/src/matchers/changeEtherBalances.ts
- waffle-chai/src/matchers/changeTokenBalance.ts
- waffle-chai/src/matchers/changeTokenBalances.ts
- waffle-chai/test/matchers/changeEtherBalanceTest.ts
- waffle-chai/test/matchers/changeEtherBalancesTest.ts
- waffle-chai/test/matchers/changeTokenBalanceTest.ts
- waffle-chai/test/matchers/changeTokenBalancesTest.ts
- `changeEtherBalance` cannot accept a string address, because it relies on `account.provider` for reading balance. `changeTokenBalance` has a provider from the contract parameter.
- Closes https://github.com/TrueFiEng/Waffle/issues/567
> 🎩 Allow string addresses in `changeTokenBalance`

- .changeset/red-rats-jump.md
- waffle-provider/src/CallHistory.ts
address with prefix 0 would thrown an error
```ts
utils.getAddress(utils.hexlify(0))
```
> 🧠 Fix error when address length less than 20
