package.json
=> Most recent solc version used

lib/matchers/overwriteBigNumberFunction.js
Fixes https://github.com/EthWorks/Waffle/issues/26
=> Replace instanceOf with BigNumber.isBigNumber

README.md, lib/waffle.js, package.json, script/buildTestContracts.js, test/compiler/compiler.js, test/compiler/contracts/LibraryConsumer.sol, test/compiler/contracts/MyLibrary.sol, test/example/example.js
Added `link` to the waffle lib.
Added usage to Readme.
=> Library linking

lib/utils.js
=> Update isWarningMessage for solcjs 5 output

lib/waffle.ts, test/deployContract.ts
=> Update deployContract to work with Infura

docs/source/configuration.rst, lib/compiler/compileSolcjs.ts, lib/compiler/findInputs.ts, lib/utils.ts, shims/solc/index.d.ts, test/compiler/wrappers/compileSolcjs.ts, test/utils.ts, yarn.lock
Added support for solc path, which can be passed to solcVersion in waffle.json.
=> Add support for solc path

package.json
https://github.com/EthWorks/Waffle/issues/110
=> Move types/ganache-core to dependencies

lib/compiler/saveOutput.ts, package.json, test/compiler/e2e.ts, test/compiler/wrappers/saveOutput.ts, test/projects/insideOut/main/config_docker.json, yarn.lock
=> Fix targetPath not working for nested paths

docs/release-notes/2.2.0.md, package.json
=> Prepare 2.2.0 release

docs/release-notes/2.3.1.md, waffle-provider/package.json, yarn.lock
=> Temporarily fix ganache version to 2.9.0-istanbul.0

docs/release-notes/2.3.2.md, waffle-cli/package.json, waffle-provider/package.json, waffle-provider/src/legacyApi.ts
This PR will enable the Buidler team to integrate their provider into our legacy API.
=> Add MockProviderLike

waffle-chai/src/matchers.ts
Closes https://github.com/EthWorks/Waffle/issues/187
=> Correct mismatched error reports

waffle-chai/README.md, waffle-chai/package.json, waffle-compiler/README.md, waffle-compiler/package.json, waffle-compiler/src/compiler.ts, waffle-provider/README.md, waffle-provider/package.json
=> Readme updates

docs/source/getting-started.rst
=> Tweaks Getting Started for latest version

waffle-compiler/src/compileDocker.ts, waffle-compiler/src/compileNative.ts, waffle-compiler/src/compiler.ts
=> Increase max output buffer size during native and docker compilation

waffle-compiler/src/getHumanReadableAbi.ts, waffle-compiler/test/compiler/humanReadableAbi.ts, waffle-compiler/test/projects/humanReadableAbi/config.json, waffle-compiler/test/projects/humanReadableAbi/config2.json, waffle-compiler/test/projects/humanReadableAbi/contracts/MyContract.sol
=> Support tuple types in the human readable abi

waffle-compiler/src/flattener.ts, waffle-compiler/test/flattener/expectedFlattenChild.sol, waffle-compiler/test/flattener/flattener.ts, waffle-compiler/test/flattener/testSource/child.sol, waffle-compiler/test/flattener/testSource/parent.sol
=> Fix problem with flat contract import order

waffle-chai/src/matchers/calledOnContract/calledOnContractValidators.ts, waffle-chai/src/matchers/calledOnContract/error.ts, waffle-chai/src/matchers/calledOnContract/utils.ts, waffle-chai/test/matchers/calledOnContract/calledOnContractValidators.test.ts
=> Improve callOnContract validation (introduce ensure, custom exceptions)

waffle-mock-contract/README.md, waffle-mock-contract/src/Doppelganger.sol, waffle-mock-contract/src/index.ts, waffle-mock-contract/test/contract.test.ts, waffle-mock-contract/test/direct.test.ts
- Mocks can call constant functions
- Mocks can execute transactions
=> Mock can call and staticcall through to other contracts

waffle-provider/src/fixtures.ts
=> Export fixture type

waffle-provider/src/fixtures.ts
=> Revert breaking change from Wallet to Signer

package.json
=> Update package.json with author and homepage

docs/source/configuration.rst, waffle-compiler/package.json, waffle-compiler/src/compileSolcjs.ts, waffle-compiler/src/config/config.ts, waffle-compiler/src/config/defaultConfig.ts, waffle-compiler/src/shims/solc.d.ts, waffle-compiler/src/utils.ts, waffle-compiler/test/compiler/wrappers/compileSolcjs.ts, waffle-compiler/test/utils.ts, yarn.lock
This PR implements solcjs caching and resolves #377.
=> Cache downloaded solcjs binaries

docs/source/matchers.rst, waffle-chai/src/index.ts, waffle-chai/src/matchers/hexEqual.ts, waffle-chai/src/types.ts, waffle-chai/test/matchers/hexEqual.test.ts
Related issue: Support Hex equal #369
=> Add hexEqual matcher

waffle-chai/src/matchers/emit.ts, waffle-chai/src/matchers/misc/transaction.ts, waffle-chai/test/matchers/events.test.ts
=> Allow asserting events on previously executed transactions

.github/workflows/CI.yml
=> Make GHA run on forks

.changeset/purple-bananas-drop.md, waffle-chai/package.json, waffle-ens/package.json, waffle-mock-contract/package.json, waffle-provider/package.json, yarn.lock
Solves https://github.com/EthWorks/Waffle/issues/580.
=> Bump Ethers

.changeset/young-paws-beam.md, waffle-chai/src/types.ts, waffle-chai/test/matchers/bigNumber.test.ts
Updated version of: #593 
Co-authored-by: [marcelomorgado](https://github.com/marcelomorgado)
=> Adjust closeTo delta type

.changeset/eighty-squids-knock.md, waffle-chai/src/matchers/bigNumber.ts, waffle-chai/test/matchers/bigNumber.test.ts
Closes https://github.com/TrueFiEng/Waffle/issues/643
=> 🌂 closeTo actual convert to BN

.changeset/shy-nails-design.md, .github/workflows/CI.yml, pnpm-lock.yaml, waffle-chai/src/matchers/revertedWith.ts, waffle-chai/test/matchers/revertedWithTest.ts, waffle-hardhat/package.json, waffle-hardhat/test/reverted.test.ts
Closes https://github.com/TrueFiEng/Waffle/issues/761
=> 🧢 Decode error string presented in newer versions of hardhat

waffle-chai/test/matchers/revertedWithTest.ts
Remove duplicate - copy-paste mistake after https://github.com/TrueFiEng/Waffle/pull/767
=> 👨‍🏭 Add a test for single quote in revert message

docs/source/matchers.rst
Closes https://github.com/TrueFiEng/Waffle/issues/453
=> 👨🏼‍🌾 Add docs for `to.emit` with events in a Library

.changeset/small-feet-beam.md, waffle-provider/src/MockProvider.ts, waffle-provider/test/MockProvider.test.ts, waffle-provider/test/MockProviderWallets.test.ts
Closes https://github.com/TrueFiEng/Waffle/issues/404
Closes https://github.com/TrueFiEng/Waffle/issues/737
=> 👩🏻‍🍳 MockProvider: Use actual wallets from ganache in `getWallets`

.changeset/rotten-glasses-camp.md, examples/typechain-example/package.json, pnpm-lock.yaml, waffle-cli/package.json, waffle-compiler/package.json, waffle-e2e/package.json, waffle-mock-contract/package.json
Closes https://github.com/TrueFiEng/Waffle/issues/591
=> 🪵 Upgrade solc

pnpm-lock.yaml
- Closes https://github.com/TrueFiEng/Waffle/issues/501
- Closes https://github.com/TrueFiEng/Waffle/issues/531
=> 🫁 Upgrade dependencies with vulnerabilities

waffle-compiler/src/compileDockerSolc.ts, waffle-compiler/test/compiler/e2e.ts, waffle-compiler/test/compiler/wrappers/compileDocker.ts, waffle-compiler/test/projects/solidity7/config_docker.json, waffle-compiler/test/projects/solidity7/config_solcjs.json, waffle-compiler/test/projects/solidity7/config_solcjs_commit.json, waffle-compiler/test/projects/solidity7/custom_contracts/Custom.sol, waffle-compiler/test/projects/solidity7/custom_contracts/MyLibrary.sol, waffle-compiler/test/projects/solidity7/custom_contracts/sub/One.sol, waffle-compiler/test/projects/solidity7/custom_contracts/sub/Two.sol, waffle-compiler/test/projects/solidity7/custom_node_modules/openzeppelin-solidity/CustomSafeMath.sol, waffle-compiler/test/projects/solidity7/custom_node_modules/openzeppelin-solidity/sub/ERC20.sol, waffle-compiler/test/projects/solidity8/config_docker.json, waffle-compiler/test/projects/solidity8/config_solcjs.json, waffle-compiler/test/projects/solidity8/config_solcjs_commit.json, waffle-compiler/test/projects/solidity8/custom_contracts/Custom.sol, waffle-compiler/test/projects/solidity8/custom_contracts/MyLibrary.sol, waffle-compiler/test/projects/solidity8/custom_contracts/sub/One.sol, waffle-compiler/test/projects/solidity8/custom_contracts/sub/Two.sol, waffle-compiler/test/projects/solidity8/custom_node_modules/openzeppelin-solidity/CustomSafeMath.sol, waffle-compiler/test/projects/solidity8/custom_node_modules/openzeppelin-solidity/sub/ERC20.sol
Closes https://github.com/TrueFiEng/Waffle/issues/495
=> 🌜 Add tests for compiling solidity 7 and 8

waffle-chai/src/index.ts, waffle-chai/src/matchers/emit.ts
Temporary measure to make it compatible with:
https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-waffle/src/waffle-chai.ts
=> 🧒 Add withArgs and withNamedArgs alongside toEmit matcher

.changeset/nervous-crabs-build.md, pnpm-lock.yaml, waffle-ens/package.json, waffle-provider/package.json
Closes https://github.com/TrueFiEng/Waffle/issues/780
=> 🦜 Bump ganache

.changeset/ten-turtles-brake.md, .github/workflows/CI.yml, waffle-chai/src/inject-call-history.ts, waffle-chai/test/matchers/revertedWithTest.ts
Follow up to https://github.com/TrueFiEng/Waffle/pull/793
=> 🛶 Updates for hardhat v2.11

.changeset/curly-years-hear.md, docs/source/ens.rst, waffle-ens/package.json, waffle-ens/src/contracts.js
Follow up to https://github.com/TrueFiEng/Waffle/pull/720
=> 🥄 Add ENS dependencies as peer dependencies

.changeset/angry-eggs-perform.md, waffle-ens/src/ENS.ts, waffle-ens/src/contracts.js
Follow up to https://github.com/TrueFiEng/Waffle/pull/801
=> 🏄 Defer an error about missing ENS peer dependencies to execution

waffle-cli/README.md
=> 🐕 Fix typos

.changeset/silly-pets-do.md, waffle-mock-contract/src/index.ts
=> 🥑 Add mock contract typing
